name: volleyball_app
description: "PlayBall - Приложение для организации спортивных игр"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_app_check: ^0.3.2+6

  # Маршрутизация
  go_router: ^15.1.2

  # Управление состоянием
  flutter_riverpod: ^2.4.9

  # Другие пакеты
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  url_launcher: ^6.2.2
  
  # AWS S3 integration
  minio: ^3.5.7
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/setka.jfif
    - assets/images/schedule/schedule_bg.png
    - .env

  fonts:
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-VariableFont_wght.ttf
          weight: 400
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
          weight: 400
